/***********************************************************************************************************************
* This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
* will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
**********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
* Included files
**********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_clock.h"
#include "fsl_lpspi.h"
#include "fsl_lpuart.h"
#include "fsl_pit.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

    /***********************************************************************************************************************
    * Definitions
    **********************************************************************************************************************/
    /* Definitions for BOARD_InitPeripherals functional group */
    /* BOARD_InitPeripherals defines for LPSPI1 */
    /* Definition of peripheral ID */
#define LPSPI_1_PERIPHERAL LPSPI1
    /* Definition of clock source */
#define LPSPI_1_CLOCK_FREQ 105600000UL
    /* Definition of peripheral ID */
#define LPUART_2_PERIPHERAL LPUART2
    /* Definition of the clock source frequency */
#define LPUART_2_CLOCK_SOURCE 80000000UL
    /* LPUART_2 interrupt vector ID (number). */
#define LPUART_2_SERIAL_RX_TX_IRQN LPUART2_IRQn
    /* LPUART_2 interrupt handler identifier. */
#define LPUART_2_SERIAL_RX_TX_IRQHANDLER LPUART2_IRQHandler
    /* BOARD_InitPeripherals defines for PIT */
    /* Definition of peripheral ID. */
#define PIT_PERIPHERAL PIT
    /* Definition of clock source frequency. */
#define PIT_CLK_FREQ 75000000UL
    /* Definition of ticks count for channel 0. */
#define PIT_0_TICKS 74U
    /* PIT interrupt vector ID (number). */
#define PIT_IRQN PIT_IRQn
    /* PIT interrupt vector priority. */
#define PIT_IRQ_PRIORITY 0
    /* PIT interrupt handler identifier. */
#define PIT_IRQHANDLER PIT_IRQHandler

    /***********************************************************************************************************************
    * Global variables
    **********************************************************************************************************************/
    extern const lpspi_master_config_t LPSPI_1_config;
    extern const lpuart_config_t LPUART_2_config;
    extern const pit_config_t PIT_config;

    /***********************************************************************************************************************
    * Initialization functions
    **********************************************************************************************************************/
    void BOARD_InitPeripherals(void);

    /***********************************************************************************************************************
    * BOARD_InitBootPeripherals function
    **********************************************************************************************************************/
    void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
