/***********************************************************************************************************************
* This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
* will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
**********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v5.0
processor: MIMXRT1052xxxxB
package_id: MIMXRT1052CVL5B
mcu_data: ksdk2_0
processor_version: 5.0.2
functionalGroups:
- name: BOARD_InitPeripherals
called_from_default_init: true
selectedCore: core0
* BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions: []
* BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
* Included files
**********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
* BOARD_InitPeripherals functional group
**********************************************************************************************************************/
/***********************************************************************************************************************
* LPSPI_1 initialization code
**********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPSPI_1'
- type: 'lpspi'
- mode: 'polling'
- type_id: 'lpspi_6e21a1e0a09f0a012d683c4f91752db8'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPSPI1'
- config_sets:
- main:
- mode: 'kLPSPI_Master'
- clockSource: 'LpspiClock'
- clockSourceFreq: 'BOARD_BootClockRUN'
- master:
- baudRate: '25000000'
- bitsPerFrame: '8'
- cpol: 'kLPSPI_ClockPolarityActiveHigh'
- cpha: 'kLPSPI_ClockPhaseFirstEdge'
- direction: 'kLPSPI_MsbFirst'
- pcsToSckDelayInNanoSec: '10'
- lastSckToPcsDelayInNanoSec: '10'
- betweenTransferDelayInNanoSec: '10'
- whichPcs: 'kLPSPI_Pcs0'
- pcsActiveHighOrLow: 'kLPSPI_PcsActiveLow'
- pinCfg: 'kLPSPI_SdiInSdoOut'
- dataOutConfig: 'kLpspiDataOutRetained'
* BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpspi_master_config_t LPSPI_1_config = {
    .baudRate = 25000000,
    .bitsPerFrame = 8,
    .cpol = kLPSPI_ClockPolarityActiveHigh,
    .cpha = kLPSPI_ClockPhaseFirstEdge,
    .direction = kLPSPI_MsbFirst,
    .pcsToSckDelayInNanoSec = 10,
    .lastSckToPcsDelayInNanoSec = 10,
    .betweenTransferDelayInNanoSec = 10,
    .whichPcs = kLPSPI_Pcs0,
    .pcsActiveHighOrLow = kLPSPI_PcsActiveLow,
    .pinCfg = kLPSPI_SdiInSdoOut,
    .dataOutConfig = kLpspiDataOutRetained
};

void LPSPI_1_init(void) {
    LPSPI_MasterInit(LPSPI_1_PERIPHERAL, &LPSPI_1_config, LPSPI_1_CLOCK_FREQ);
}

/***********************************************************************************************************************
* LPUART_2 initialization code
**********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART_2'
- type: 'lpuart'
- mode: 'interrupts'
- type_id: 'lpuart_bebe3e12b6ec22bbd14199038f2bf459'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART2'
- config_sets:
- lpuartConfig_t:
- lpuartConfig:
- clockSource: 'LpuartClock'
- lpuartSrcClkFreq: 'BOARD_BootClockRUN'
- baudRate_Bps: '256000'
- parityMode: 'kLPUART_ParityDisabled'
- dataBitsCount: 'kLPUART_EightDataBits'
- isMsb: 'false'
- stopBitCount: 'kLPUART_OneStopBit'
- txFifoWatermark: '0'
- rxFifoWatermark: '1'
- enableRxRTS: 'false'
- enableTxCTS: 'false'
- txCtsSource: 'kLPUART_CtsSourcePin'
- txCtsConfig: 'kLPUART_CtsSampleAtStart'
- rxIdleType: 'kLPUART_IdleTypeStartBit'
- rxIdleConfig: 'kLPUART_IdleCharacter1'
- enableTx: 'true'
- enableRx: 'true'
- interruptsCfg:
- interrupts: 'kLPUART_TxDataRegEmptyInterruptEnable kLPUART_TransmissionCompleteInterruptEnable kLPUART_RxDataRegFullInterruptEnable kLPUART_RxOverrunInterruptEnable'
- interrupt_vectors:
- enable_rx_tx_irq: 'true'
- interrupt_rx_tx:
- IRQn: 'LPUART2_IRQn'
- enable_priority: 'false'
- enable_custom_name: 'false'
- quick_selection: 'QuickSelection1'
* BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART_2_config = {
    .baudRate_Bps = 256000,
    .parityMode = kLPUART_ParityDisabled,
    .dataBitsCount = kLPUART_EightDataBits,
    .isMsb = false,
    .stopBitCount = kLPUART_OneStopBit,
    .txFifoWatermark = 0,
    .rxFifoWatermark = 1,
    .enableRxRTS = false,
    .enableTxCTS = false,
    .txCtsSource = kLPUART_CtsSourcePin,
    .txCtsConfig = kLPUART_CtsSampleAtStart,
    .rxIdleType = kLPUART_IdleTypeStartBit,
    .rxIdleConfig = kLPUART_IdleCharacter1,
    .enableTx = true,
    .enableRx = true
};

void LPUART_2_init(void) {
    LPUART_Init(LPUART_2_PERIPHERAL, &LPUART_2_config, LPUART_2_CLOCK_SOURCE);
    LPUART_EnableInterrupts(LPUART_2_PERIPHERAL, kLPUART_TxDataRegEmptyInterruptEnable | kLPUART_TransmissionCompleteInterruptEnable | kLPUART_RxDataRegFullInterruptEnable | kLPUART_RxOverrunInterruptEnable);
    /* Enable interrupt LPUART2_IRQn request in the NVIC */
    EnableIRQ(LPUART_2_SERIAL_RX_TX_IRQN);
}

/***********************************************************************************************************************
* PIT initialization code
**********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PIT'
- type: 'pit'
- mode: 'LPTMR_GENERAL'
- type_id: 'pit_a4782ba5223c8a2527ba91aeb2bc4159'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'PIT'
- config_sets:
- fsl_pit:
- enableRunInDebug: 'false'
- enableSharedInterrupt: 'true'
- sharedInterrupt:
- IRQn: 'PIT_IRQn'
- enable_priority: 'true'
- priority: '0'
- enable_custom_name: 'true'
- handler_custom_name: 'PIT_IRQHANDLER'
- timingConfig:
- clockSource: 'BusInterfaceClock'
- clockSourceFreq: 'BOARD_BootClockRUN'
- channels:
- 0:
- channelNumber: '0'
- enableChain: 'false'
- timerPeriod: '1us'
- startTimer: 'true'
- enableInterrupt: 'true'
* BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const pit_config_t PIT_config = {
    .enableRunInDebug = false
};

void PIT_init(void) {
    /* Initialize the PIT. */
    PIT_Init(PIT_PERIPHERAL, &PIT_config);
    /* Set channel 0 period to 1 µs (75 ticks). */
    PIT_SetTimerPeriod(PIT_PERIPHERAL, kPIT_Chnl_0, PIT_0_TICKS);
    /* Enable interrupts from channel 0. */
    PIT_EnableInterrupts(PIT_PERIPHERAL, kPIT_Chnl_0, kPIT_TimerInterruptEnable);
    /* Interrupt vector PIT_IRQN priority settings in the NVIC */
    NVIC_SetPriority(PIT_IRQN, PIT_IRQ_PRIORITY);
    /* Enable interrupt PIT_IRQN request in the NVIC */
    EnableIRQ(PIT_IRQN);
    /* Start channel 0. */
    PIT_StartTimer(PIT_PERIPHERAL, kPIT_Chnl_0);
}

/***********************************************************************************************************************
* Initialization functions
**********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
    /* Initialize components */
    //LPSPI_1_init();
    //LPUART_2_init();
    //PIT_init();
}

/***********************************************************************************************************************
* BOARD_InitBootPeripherals function
**********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
    BOARD_InitPeripherals();
}
