/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_SD_B0_01 (coord J3), SPI1PCS0 */
#define BOARD_INITPINS_SPI1PCS0_PERIPHERAL                                LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SPI1PCS0_SIGNAL                                      PCS0   /*!< LPSPI1 signal: PCS0 */

/* GPIO_SD_B0_00 (coord J4), SPI1SCK */
#define BOARD_INITPINS_SPI1SCK_PERIPHERAL                                 LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SPI1SCK_SIGNAL                                        SCK   /*!< LPSPI1 signal: SCK */

/* GPIO_SD_B0_02 (coord J1), SPI1SDO */
#define BOARD_INITPINS_SPI1SDO_PERIPHERAL                                 LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SPI1SDO_SIGNAL                                        SDO   /*!< LPSPI1 signal: SDO */

/* GPIO_SD_B0_03 (coord K1), SPI1SDI */
#define BOARD_INITPINS_SPI1SDI_PERIPHERAL                                 LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SPI1SDI_SIGNAL                                        SDI   /*!< LPSPI1 signal: SDI */

/* GPIO_B1_14 (coord C14), TFTRES */
#define BOARD_INITPINS_TFTRES_GPIO                                         GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_TFTRES_PORT                                         GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_TFTRES_PIN                                            30U   /*!< GPIO2 pin index: 30 */

/* GPIO_SD_B1_00 (coord L5), TFTDC */
#define BOARD_INITPINS_TFTDC_GPIO                                          GPIO3   /*!< GPIO device name: GPIO3 */
#define BOARD_INITPINS_TFTDC_PORT                                          GPIO3   /*!< PORT device name: GPIO3 */
#define BOARD_INITPINS_TFTDC_PIN                                              0U   /*!< GPIO3 pin index: 0 */

/* GPIO_AD_B1_03 (coord M12), UART2RX */
#define BOARD_INITPINS_UART2RX_PERIPHERAL                                LPUART2   /*!< Device name: LPUART2 */
#define BOARD_INITPINS_UART2RX_SIGNAL                                         RX   /*!< LPUART2 signal: RX */

/* GPIO_AD_B1_02 (coord L11), UART2TX */
#define BOARD_INITPINS_UART2TX_PERIPHERAL                                LPUART2   /*!< Device name: LPUART2 */
#define BOARD_INITPINS_UART2TX_SIGNAL                                         TX   /*!< LPUART2 signal: TX */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
